#!/usr/bin/env python

import RPi.GPIO as GPIO
import time
GPIO.setmode(GPIO.BOARD)
GPIO.setup(16, GPIO.OUT)
GPIO.setup(18, GPIO.OUT)
p = GPIO.PWM(16, 500)

def SpinMotor(direction, num_steps):
    GPIO.output(18, direction)
    while num_steps > 0:
        p.start(1)
        time.sleep(0.01)
        num_step -= 1
    p.stop()
    GPIO.cleanup()
    return True
direction_input = input('please enter cw or ccw:')
num_steps = input('please eneter the number of steps:')
if direction_input == 'cw':
    SpinMotor(False, num_steps)
else:
    SpinMotor(True, num_steps)
